DR.WB SSR LIVE RELOADING
open-source-labs/vno pull request #106
Opened 2021-04-15 19:56 UTC by deadxears

GOING INTO ALPHA

2021-04-15 20:00 UTC, dwaynerichards approved these changes

2021-04-15 20:00 UTC, dwaynerichards approved these changes
reviewed.

2021-04-15 20:01 UTC, dwaynerichards approved these changes
reviewed

2021-04-15 20:01 UTC, dwaynerichards approved these changes

2021-04-15 20:01 UTC, HeroesOfOnesAndZeros approved these changes
reviewed

2021-04-15 22:31 UTC, buttercubz commented on core/cli/templates.ts
> +import { join, dirname} from "https://deno.land/std@0.63.0/path/mod.ts";
I could update to [`std@0.93.0`](https://deno.land/std@0.93.0) which already has many bug solved

2021-04-15 22:36 UTC, buttercubz commented on core/cli/commands.ts
> +import { existsSync } from 'https://deno.land/std/fs/mod.ts';
try not to use unversioned url to avoid breaking changes

2021-04-15 22:42 UTC, buttercubz commented on core/utils/livereload.ts
> +    eval(event.data);
please don't use `eval()` it's a very risk

2021-04-15 22:42 UTC, buttercubz commented on core/cli/dev.ts
> +      ws.send('window.location.reload();');
https://github.com/open-source-labs/vno/pull/106/files#r614435145

2021-04-15 22:46 UTC, buttercubz requested changes
For now looks promising

2021-04-17 00:10 UTC, unknownbreaker commented
Thanks for giving a once over @buttercubz, and great points regarding `eval` and versioning. We'll revisit this.

2021-04-28 16:04 UTC, buttercubz approved these changes

2021-05-05 00:35 UTC, closed without merging

2021-05-05 00:35 UTC, HeroesOfOnesAndZeros commented
fixed errors, going to resubmit pull request from oslabs beta